// <auto-generated />
using System;
using IORManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IORManager.Migrations
{
    [DbContext(typeof(IORManagerContext))]
    [Migration("20260804201446_AddInvoiceComments")]
    partial class AddInvoiceComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IORManager.Models.AccountingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("IsrRatePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AccountingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsrRatePercent = 0m
                        });
                });

            modelBuilder.Entity("IORManager.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultNcfCategory")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("DefaultPaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("IORManager.Models.DocumentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("QuoteId");

                    b.ToTable("DocumentLines");
                });

            modelBuilder.Entity("IORManager.Models.FinancialDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("FinancialDocument");

                    b.HasDiscriminator<string>("DocumentType").HasValue("FinancialDocument");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IORManager.Models.FiscalRegime", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("InvoiceCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FiscalRegimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "B01",
                            InvoiceCount = 0,
                            Name = "Factura de Crédito Fiscal"
                        },
                        new
                        {
                            Id = 2,
                            Code = "B02",
                            InvoiceCount = 0,
                            Name = "Factura de Consumo"
                        },
                        new
                        {
                            Id = 3,
                            Code = "B03",
                            InvoiceCount = 0,
                            Name = "Notas de Débito"
                        },
                        new
                        {
                            Id = 4,
                            Code = "B04",
                            InvoiceCount = 0,
                            Name = "Notas de Crédito"
                        },
                        new
                        {
                            Id = 5,
                            Code = "B11",
                            InvoiceCount = 0,
                            Name = "Comprobante de Compras"
                        },
                        new
                        {
                            Id = 6,
                            Code = "B12",
                            InvoiceCount = 0,
                            Name = "Registro Único de Ingresos"
                        },
                        new
                        {
                            Id = 7,
                            Code = "B13",
                            InvoiceCount = 0,
                            Name = "Comprobante para Gastos Menores"
                        },
                        new
                        {
                            Id = 8,
                            Code = "B14",
                            InvoiceCount = 0,
                            Name = "Comprobante para Regímenes Especiales"
                        },
                        new
                        {
                            Id = 9,
                            Code = "B15",
                            InvoiceCount = 0,
                            Name = "Comprobante Gubernamental"
                        },
                        new
                        {
                            Id = 10,
                            Code = "B16",
                            InvoiceCount = 0,
                            Name = "Comprobante para Exportaciones"
                        },
                        new
                        {
                            Id = 11,
                            Code = "B17",
                            InvoiceCount = 0,
                            Name = "Comprobante para Pagos al Exterior"
                        },
                        new
                        {
                            Id = 12,
                            Code = "E31",
                            InvoiceCount = 0,
                            Name = "e-Crédito Fiscal"
                        },
                        new
                        {
                            Id = 13,
                            Code = "E32",
                            InvoiceCount = 0,
                            Name = "e-Consumo"
                        },
                        new
                        {
                            Id = 14,
                            Code = "E33",
                            InvoiceCount = 0,
                            Name = "e-Notas de Débito"
                        },
                        new
                        {
                            Id = 15,
                            Code = "E34",
                            InvoiceCount = 0,
                            Name = "e-Notas de Crédito"
                        },
                        new
                        {
                            Id = 16,
                            Code = "E41",
                            InvoiceCount = 0,
                            Name = "e-Comprobante de Compras"
                        },
                        new
                        {
                            Id = 17,
                            Code = "E43",
                            InvoiceCount = 0,
                            Name = "e-Comprobante para Gastos Menores"
                        },
                        new
                        {
                            Id = 18,
                            Code = "E44",
                            InvoiceCount = 0,
                            Name = "e-Comprobante para Regímenes Especiales"
                        },
                        new
                        {
                            Id = 19,
                            Code = "E45",
                            InvoiceCount = 0,
                            Name = "e-Comprobante Gubernamental"
                        },
                        new
                        {
                            Id = 20,
                            Code = "E46",
                            InvoiceCount = 0,
                            Name = "e-Comprobante para Exportaciones"
                        },
                        new
                        {
                            Id = 21,
                            Code = "E47",
                            InvoiceCount = 0,
                            Name = "e-Comprobante para Pagos al Exterior"
                        });
                });

            modelBuilder.Entity("IORManager.Models.InvoiceNumberSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InvoiceNumberSequences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NextNumber = 1
                        });
                });

            modelBuilder.Entity("IORManager.Models.NcfSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("NcfSequences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "B02",
                            NextNumber = 1L
                        });
                });

            modelBuilder.Entity("IORManager.Models.OrderExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasInvoice")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ReceiptFileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ReceiptFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("ReceiptFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReceiptUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rnc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderExpenses");
                });

            modelBuilder.Entity("IORManager.Models.PurchaseOrderAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderAttachments");
                });

            modelBuilder.Entity("IORManager.Models.QuoteAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteAttachments");
                });

            modelBuilder.Entity("IORManager.Models.ReceiptPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptPayments");
                });

            modelBuilder.Entity("IORManager.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IORManager.Models.AccountPayable", b =>
                {
                    b.HasBaseType("IORManager.Models.FinancialDocument");

                    b.Property<string>("CustomerPO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("AccountPayable");
                });

            modelBuilder.Entity("IORManager.Models.Invoice", b =>
                {
                    b.HasBaseType("IORManager.Models.FinancialDocument");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomerContact")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerPONumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpirationDateOverride")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FiscalRegimeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvoiceGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ItbisRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("NcfCategory")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NcfNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FiscalRegimeId");

                    b.HasIndex("NcfNumber")
                        .IsUnique()
                        .HasFilter("[NcfNumber] IS NOT NULL");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasFilter("[QuoteId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Invoice");
                });

            modelBuilder.Entity("IORManager.Models.PurchaseOrder", b =>
                {
                    b.HasBaseType("IORManager.Models.FinancialDocument");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Order_ConvertedAt");

                    b.Property<Guid?>("ConvertedInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Order_ConvertedInvoiceId");

                    b.Property<string>("InvestmentNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("ConvertedInvoiceId")
                        .IsUnique()
                        .HasFilter("[Order_ConvertedInvoiceId] IS NOT NULL");

                    b.HasIndex("QuoteId");

                    b.ToTable("FinancialDocument", t =>
                        {
                            t.Property("QuoteId")
                                .HasColumnName("PurchaseOrder_QuoteId");

                            t.Property("Status")
                                .HasColumnName("PurchaseOrder_Status");
                        });

                    b.HasDiscriminator().HasValue("PurchaseOrder");
                });

            modelBuilder.Entity("IORManager.Models.Quote", b =>
                {
                    b.HasBaseType("IORManager.Models.FinancialDocument");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ConvertedAt");

                    b.Property<Guid?>("ConvertedInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ConvertedInvoiceId");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomerContact")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerPONumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ItbisRate")
                        .HasColumnType("decimal(5,4)");

                    b.HasIndex("ConvertedInvoiceId")
                        .IsUnique()
                        .HasFilter("[ConvertedInvoiceId] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.ToTable("FinancialDocument", t =>
                        {
                            t.Property("Comments")
                                .HasColumnName("Quote_Comments");

                            t.Property("CustomerAddress")
                                .HasColumnName("Quote_CustomerAddress");

                            t.Property("CustomerContact")
                                .HasColumnName("Quote_CustomerContact");

                            t.Property("CustomerId")
                                .HasColumnName("Quote_CustomerId");

                            t.Property("CustomerPONumber")
                                .HasColumnName("Quote_CustomerPONumber");

                            t.Property("ItbisRate")
                                .HasColumnName("Quote_ItbisRate");
                        });

                    b.HasDiscriminator().HasValue("Quote");
                });

            modelBuilder.Entity("IORManager.Models.Receipt", b =>
                {
                    b.HasBaseType("IORManager.Models.FinancialDocument");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Receipt");
                });

            modelBuilder.Entity("IORManager.Models.DocumentLine", b =>
                {
                    b.HasOne("IORManager.Models.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IORManager.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IORManager.Models.Quote", "Quote")
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Invoice");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("IORManager.Models.OrderExpense", b =>
                {
                    b.HasOne("IORManager.Models.PurchaseOrder", "Order")
                        .WithMany("Expenses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IORManager.Models.PurchaseOrderAttachment", b =>
                {
                    b.HasOne("IORManager.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Attachments")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("IORManager.Models.QuoteAttachment", b =>
                {
                    b.HasOne("IORManager.Models.Quote", "Quote")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("IORManager.Models.ReceiptPayment", b =>
                {
                    b.HasOne("IORManager.Models.Receipt", "Receipt")
                        .WithMany("Payments")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("IORManager.Models.AccountPayable", b =>
                {
                    b.HasOne("IORManager.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("IORManager.Models.Invoice", b =>
                {
                    b.HasOne("IORManager.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IORManager.Models.FiscalRegime", "FiscalRegime")
                        .WithMany("Invoices")
                        .HasForeignKey("FiscalRegimeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");

                    b.Navigation("FiscalRegime");
                });

            modelBuilder.Entity("IORManager.Models.PurchaseOrder", b =>
                {
                    b.HasOne("IORManager.Models.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("IORManager.Models.Quote", b =>
                {
                    b.HasOne("IORManager.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IORManager.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("IORManager.Models.FiscalRegime", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("IORManager.Models.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("IORManager.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Expenses");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("IORManager.Models.Quote", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("IORManager.Models.Receipt", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
